1. Import the numpy package under the name np


In [1]:
import numpy as np

Create a null vector of size 10

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1 

In [9]:
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [16]:
vector_range_39 = np.arange(10,50) 
print(vector_range_39)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
vector_10 = np.arange(0,9)
vector_shift_matrix = vector_10.reshape((3,3))
print(vector_shift_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [83]:
lst_a =  [1,2,0,0,4,0] #x[np.nonzero(x)]
x = np.array([1, 2, 0, 0, 4, 0])
nonzero_elements = x[np.nonzero(x)]
print(nonzero_elements)

[1 2 4]


Create a 3x3 identity matrix

In [65]:
null_vector_9 = np.zeros(9)

In [66]:
null_vector_9

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
null_vector_9[0] = 1 #1st position

In [68]:
null_vector_9

array([1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
null_vector_9[4] = 1 #5th position

In [70]:
null_vector_9

array([1., 0., 0., 0., 1., 0., 0., 0., 0.])

In [71]:
null_vector_9[1] = 0 #2nd position

In [72]:
null_vector_9[8] = 1 #9th position

In [64]:
identity_matrix = null_vector_9.reshape(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#alternative with np.eye

In [80]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values

In [103]:
three_array = np.random.random((3,3,3))
print(three_array)

[[[0.81765563 0.91189329 0.61376717]
  [0.67383965 0.14076591 0.16850972]
  [0.32638864 0.43360514 0.3144987 ]]

 [[0.2479384  0.7656333  0.06579374]
  [0.62591829 0.98199963 0.50097952]
  [0.25946205 0.93172954 0.31122655]]

 [[0.28367631 0.4505895  0.3703236 ]
  [0.68015618 0.18774197 0.54348271]
  [0.77289119 0.03755183 0.01988   ]]]


Create a 10x10 array with random values and find the minimum and maximum values

In [116]:
ten_array = np.random.random((10,10))
print(ten_array)

[[0.38637227 0.01542118 0.09984809 0.58740932 0.24372913 0.25580718
  0.33036029 0.64218339 0.9236108  0.37740084]
 [0.16399645 0.53664986 0.7706099  0.52718128 0.17296428 0.8669011
  0.9502463  0.9756953  0.47570963 0.23466387]
 [0.41979803 0.17013522 0.3603842  0.32865729 0.87833265 0.20217541
  0.05984551 0.18232849 0.27788712 0.25064732]
 [0.08789804 0.44182693 0.24557035 0.73240846 0.57497347 0.29643664
  0.53606691 0.17027544 0.31351978 0.37604788]
 [0.85238807 0.03025556 0.39512051 0.38935056 0.85549359 0.72012873
  0.19223689 0.13794046 0.63904025 0.23633321]
 [0.43738014 0.61929376 0.42696218 0.19172729 0.09216066 0.84047584
  0.68314736 0.53938776 0.03586261 0.12911168]
 [0.53355185 0.59463381 0.96177937 0.44289395 0.66195243 0.11058826
  0.29407871 0.99964947 0.74444114 0.48776905]
 [0.74526476 0.25389758 0.11428139 0.41404061 0.13475499 0.68032472
  0.24488035 0.73645236 0.98555434 0.16724026]
 [0.41271573 0.04540567 0.46901076 0.37005801 0.56600795 0.01840381
  0.90570721 

In [117]:
max_value = np.max(ten_array)
min_value = np.min(ten_array)
print(max_value)
print(min_value)

0.9996494722953458
0.015421180298313075


Create a random vector of size 30 and find the mean value

In [120]:
rand_vect = np.random.rand(30)
print(rand_vect)

[0.06469386 0.67376546 0.61340163 0.44028236 0.15379033 0.81705701
 0.86311709 0.92655185 0.56311774 0.27363379 0.81273418 0.47915991
 0.73367092 0.51630888 0.8272259  0.38642213 0.88807894 0.03048831
 0.48791989 0.29996862 0.70655218 0.56001606 0.48642023 0.1725938
 0.78504052 0.30456074 0.31225749 0.97554087 0.45275943 0.53776713]


In [121]:
np.mean(rand_vect)

0.5381632416514843

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [124]:
vec_range_25 = np.zeros(25)

In [126]:
matrix_range_25 = vec_range_25.reshape(5,5)

In [127]:
matrix_range_25

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [128]:
matrix_range_25[5] = 1
matrix_range_25[11] = 2
matrix_range_25[17] = 3
matrix_range_25[23] = 4


IndexError: index 5 is out of bounds for axis 0 with size 5