1. Import the numpy package under the name np


In [1]:
import numpy as np

Create a null vector of size 10

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1 

In [10]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [16]:
vector_range_39 = np.arange(10,50) 
print(vector_range_39)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8

In [219]:
vector_9 = np.arange(0,9)
vector_shift_matrix = vector_9.reshape((3,3))
print(vector_shift_matrix)
#vector_9 = np.arange(0,9).reshape((3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [83]:
lst_a =  [1,2,0,0,4,0] #x[np.nonzero(x)]
x = np.array([1, 2, 0, 0, 4, 0])
nonzero_elements = x[np.nonzero(x)]
print(nonzero_elements)

#for indices: x = np.nonzero(x) ---(0,1,4)

#or use help function help(np.nonzero)

[1 2 4]


Create a 3x3 identity matrix

In [65]:
null_vector_9 = np.zeros(9)

In [66]:
null_vector_9

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
null_vector_9[0] = 1 #1st position

In [68]:
null_vector_9

array([1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
null_vector_9[4] = 1 #5th position

In [70]:
null_vector_9

array([1., 0., 0., 0., 1., 0., 0., 0., 0.])

In [71]:
null_vector_9[1] = 0 #2nd position

In [72]:
null_vector_9[8] = 1 #9th position

In [64]:
identity_matrix = null_vector_9.reshape(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#alternative with np.eye

In [80]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values

In [103]:
three_array = np.random.random((3,3,3))
print(three_array)

[[[0.81765563 0.91189329 0.61376717]
  [0.67383965 0.14076591 0.16850972]
  [0.32638864 0.43360514 0.3144987 ]]

 [[0.2479384  0.7656333  0.06579374]
  [0.62591829 0.98199963 0.50097952]
  [0.25946205 0.93172954 0.31122655]]

 [[0.28367631 0.4505895  0.3703236 ]
  [0.68015618 0.18774197 0.54348271]
  [0.77289119 0.03755183 0.01988   ]]]


Create a 10x10 array with random values and find the minimum and maximum values

In [116]:
ten_array = np.random.random((10,10))
print(ten_array)

[[0.38637227 0.01542118 0.09984809 0.58740932 0.24372913 0.25580718
  0.33036029 0.64218339 0.9236108  0.37740084]
 [0.16399645 0.53664986 0.7706099  0.52718128 0.17296428 0.8669011
  0.9502463  0.9756953  0.47570963 0.23466387]
 [0.41979803 0.17013522 0.3603842  0.32865729 0.87833265 0.20217541
  0.05984551 0.18232849 0.27788712 0.25064732]
 [0.08789804 0.44182693 0.24557035 0.73240846 0.57497347 0.29643664
  0.53606691 0.17027544 0.31351978 0.37604788]
 [0.85238807 0.03025556 0.39512051 0.38935056 0.85549359 0.72012873
  0.19223689 0.13794046 0.63904025 0.23633321]
 [0.43738014 0.61929376 0.42696218 0.19172729 0.09216066 0.84047584
  0.68314736 0.53938776 0.03586261 0.12911168]
 [0.53355185 0.59463381 0.96177937 0.44289395 0.66195243 0.11058826
  0.29407871 0.99964947 0.74444114 0.48776905]
 [0.74526476 0.25389758 0.11428139 0.41404061 0.13475499 0.68032472
  0.24488035 0.73645236 0.98555434 0.16724026]
 [0.41271573 0.04540567 0.46901076 0.37005801 0.56600795 0.01840381
  0.90570721 

In [117]:
max_value = np.max(ten_array)
min_value = np.min(ten_array)
print(max_value)
print(min_value)

0.9996494722953458
0.015421180298313075


Create a random vector of size 30 and find the mean value

In [120]:
rand_vect = np.random.rand(30)
print(rand_vect)

[0.06469386 0.67376546 0.61340163 0.44028236 0.15379033 0.81705701
 0.86311709 0.92655185 0.56311774 0.27363379 0.81273418 0.47915991
 0.73367092 0.51630888 0.8272259  0.38642213 0.88807894 0.03048831
 0.48791989 0.29996862 0.70655218 0.56001606 0.48642023 0.1725938
 0.78504052 0.30456074 0.31225749 0.97554087 0.45275943 0.53776713]


In [121]:
np.mean(rand_vect)

0.5381632416514843

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [142]:
vec_range_25 = np.zeros(25)
vec_range_25[5] = 1
vec_range_25[11]=2
vec_range_25[17]=3
vec_range_25[23]=4
matrix_range_25 = vec_range_25.reshape(5,5)
print(matrix_range_25)

#or np.diag([1,2,3,4],-1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


Normalize a 5x5 random matrix

In [154]:
rand_matrix_5 = np.random.rand(5,5)

In [151]:
rand_matrix_5

array([[0.09527479, 0.55076985, 0.849994  , 0.06407341, 0.21678919],
       [0.43657232, 0.22759778, 0.9408623 , 0.85772395, 0.00830763],
       [0.99378011, 0.30724663, 0.89755718, 0.93857317, 0.64662938],
       [0.7018802 , 0.81039544, 0.35055347, 0.88906258, 0.38491618],
       [0.8989015 , 0.80220553, 0.58611733, 0.5998218 , 0.31998218]])

In [152]:
# compute the mean of each column
col_mean = np.mean(rand_matrix_5 ,axis=0)
# normalize each column by subtracting its mean and dividing by its standard deviation
arr_normalized = (rand_matrix_5 - col_mean)/np.std(rand_matrix_5 ,axis=0)
print(arr_normalized)  #normalised value can also be called the z score.

[[-1.62324758  0.04590568  0.55725152 -1.86515485 -0.47125658]
 [-0.57795875 -1.28740032  0.96241757  0.57845022 -1.46833968]
 [ 1.12859645 -0.9587943   0.76932752  0.82738042  1.58449548]
 [ 0.23459728  1.11703897 -1.6696676   0.67494011  0.33282696]
 [ 0.8380126   1.08324997 -0.61932901 -0.21561589  0.02227382]]


In [224]:
z = np.arange(1000)
np.random.shuffle(z)
n = 10
y = np.argsort(z)
print(z[y[-n:]])

[990 991 992 993 994 995 996 997 998 999]


How to find common values between two arrays?

In [161]:
intersection_1 = np.intersect1d(rand_matrix_5,arr_normalized)
print(intersection_1)

[]


In [158]:
list_left = [1,4,5,6,7,8,92]
list_right = [3,4,2,5,6,7,89]

In [160]:
intersection = np.intersect1d(list_left, list_right)
print(intersection)

[4 5 6 7]


Create a random vector of size 10 and sort it

In [166]:
unsorted_vector = np.random.rand(10)
sorted_vector = np.sort(unsorted_vector)
print(sorted_vector)

[0.05412994 0.10373939 0.17072783 0.3410947  0.39776338 0.45143049
 0.46403726 0.65254141 0.67778324 0.7672618 ]


Create random vector of size 10 and replace the maximum value by 0

In [174]:
rand_vect_10 = np.random.rand(10)
#sort variable list and replace max value by 0
np.sort(rand_vect_10)
rand_vect_10[-1] = 0
print(rand_vect_10)

[0.47099937 0.48560804 0.41332464 0.53395711 0.164955   0.29538543
 0.26116343 0.65354476 0.12393693 0.        ]


In [184]:
x = np.random.rand(10)  # Create a random vector of size 10
max_index = np.argmax(x)  # Find the index of the highest value
x[max_index] = 0  # Replace the highest value in the vector with zero
print(x)





[0.15658338 0.30933228 0.         0.39248529 0.07541362 0.66619209
 0.63120414 0.47285234 0.06111476 0.56706352]


Subtract the mean of each row of a matrix 

In [185]:
arr_normalized

array([[-1.62324758,  0.04590568,  0.55725152, -1.86515485, -0.47125658],
       [-0.57795875, -1.28740032,  0.96241757,  0.57845022, -1.46833968],
       [ 1.12859645, -0.9587943 ,  0.76932752,  0.82738042,  1.58449548],
       [ 0.23459728,  1.11703897, -1.6696676 ,  0.67494011,  0.33282696],
       [ 0.8380126 ,  1.08324997, -0.61932901, -0.21561589,  0.02227382]])

In [201]:

# Calculate the mean along each row
submean = np.mean(arr_normalized, axis =1, keepdims = True)
#The keepdims=True parameter is set to retain the dimensions of the mean array, resulting in a column vector submean.
submean_matrix = arr_normalized - submean 
print("Matrix minus mean value of each row:")
print(submean_matrix)


Matrix minus mean value of each row:
[[-0.95194722  0.71720604  1.22855188 -1.19385449  0.20004378]
 [-0.21939256 -0.92883413  1.32098376  0.93701641 -1.10977348]
 [ 0.45839534 -1.62899542  0.09912641  0.1571793   0.91429436]
 [ 0.09665014  0.97909183 -1.80761475  0.53699297  0.19487982]
 [ 0.61629431  0.86153167 -0.84104731 -0.43733419 -0.19944448]]


17. How to get the n largest values of an array (★★★)
#example from https://stackoverflow.com/questions/10337533/a-fast-way-to-find-the-largest-n-elements-in-an-numpy-array


In [203]:

test = np.array([9,1,3,4,8,7,2,5,6,0])

temp = np.argpartition(-test, 4)
result_args = temp[:4]

temp = np.partition(-test, 4)
result = -temp[:4]
print(result_args)
print(result)

[0 4 8 5]
[9 8 6 7]


In [205]:
 a = np.arange(10000)

np.random.shuffle(a)

%timeit np.argsort(a)
#1000 loops, best of 3: 1.02 ms per loop

%timeit np.argpartition(a, 100)
#10000 loops, best of 3: 139 us per loop

%timeit np.argpartition(a, 1000)
#10000 loops, best of 3: 141 us per loop

550 µs ± 20.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
95.5 µs ± 7.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
95.4 µs ± 3.73 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Create a random 5*3 matrix and replace items that are larger than 4 by their squares

In [215]:
cool_matrix = np.random.rand(3,5)

In [213]:
cool_matrix

array([[0.50816123, 0.87025786, 0.45047001, 0.1778567 , 0.34154966],
       [0.73273193, 0.59605472, 0.78614992, 0.18080837, 0.32245675],
       [0.898796  , 0.89562128, 0.93188839, 0.20768581, 0.3348637 ]])

In [217]:
squared_matrix = np.where(cool_matrix > 4, cool_matrix**2, cool_matrix)
print(squared_matrix)

[[0.04584153 0.05753622 0.89975584 0.99575204 0.39089434]
 [0.36959939 0.84854838 0.66447935 0.06901879 0.64102788]
 [0.15023225 0.8463277  0.36476888 0.96893147 0.14259033]]


In [234]:
my_list = [1,2,3]
list(map(lambda x: x **2, my_list))



[1, 4, 9]

In [230]:
def func(x):
    return x**2

In [236]:
list(map(func,my_list))

[1, 4, 9]

In [237]:
my_list2 = ['hi','oh','bye']
dict(zip(my_list,my_list2))

{1: 'hi', 2: 'oh', 3: 'bye'}