## Pandas Data Frames

- What Is Pandas?
- Pandas vs Numpy 
- Pandas Data Frame Intro
- Pandas Data Frame fundamental operations
    - Creating
    - Selecting/indexing
    - Inserting rows/columns
    - Setting data
    - Filtering
    - Dropping rows/ columns
- Dealing with Missing values

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from IPython.display import Image
from IPython.display import HTML
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))


Matplotlib is building the font cache; this may take a moment.
Fontconfig warning: ignoring UTF-8: not a valid region tag


In [2]:
from IPython.display import display,Image, HTML

CSS = """
.output {
    align-items: center;
}
div.output_area {
    width: 80%;
}
"""
HTML('<style>{}</style>'.format(CSS))

# What is Pandas?


### - Pandas is an open-source library built on top of Numpy Package.
- https://github.com/pandas-dev/pandas
- https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/pandas/core/frame.py

### - Enables working with tabular and labeled data easily and intuitively

### - Pandas data structures are:
    - Series
    - Index
    - Data Frame
    

## Quick refresher to Numpy Arrays
- contains Numerical ***Homogeneous*** Data
- may contain multi dimensional array elements.
- used for performing various numerical computations and processing of the multidimensional and single-dimensional array elements.

In [21]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

two_dim_arr = np.random.randint(10, size=(3, 4))  # Two-dimensional array
three_dim_arr = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array


### A two dimensional Array example...

In [22]:
print("Two Dimentional Array")
two_dim_arr

Two Dimentional Array


array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

### What I mean by Homogeneous...

In [23]:
print(two_dim_arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


**two_dim_arr[0,0] = "Hello"**

In [24]:
#printmd("***Oops....***")
two_dim_arr[0,0] = "Hello"    #if you convert str and int to an array, all the arguments will be converted to str

ValueError: invalid literal for int() with base 10: 'Hello'

### You can directly and simply form the DataFrame from the 2D array

In [25]:
import pandas as pd

In [26]:

print("Data Frame formed by 2D Array")
#printmd("***df=pd.DataFrame(two_dim_arr)***")
df=pd.DataFrame(two_dim_arr)
df

Data Frame formed by 2D Array


0  1  2  3
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6

### Pandas Data Frame is Heterogeneous!
**df.iloc[0,0]="Hello"**

### Pandas Data Frame labels the data with Indices and Columns labels
pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

In [27]:
np.random.randint(10,size=(3,2))

array([[5, 9],
       [4, 4],
       [6, 4]])

In [28]:
##np.random.seed(0)
foo_df=pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c']
                 )

In [29]:
foo_df

foo  bar
a    4    3
b    4    4
c    8    4

### Pandas DataFrame is relevant for statistical observations/data points with various types of variables (categorical, etc) 

In [30]:
Image("res/Tidy_census.png")

FileNotFoundError: No such file or directory: 'res/Tidy_census.png'

FileNotFoundError: No such file or directory: 'res/Tidy_census.png'

<IPython.core.display.Image object>

### It's intuitive...  Look how convenient it is

In [31]:
people_df= pd.read_csv("data/people.csv")
people_df

FileNotFoundError: [Errno 2] No such file or directory: 'data/people.csv'

In [ ]:
Image('res/excel-to-pandas.png')

source: https://jalammar.github.io/

### Describing the Data Frame...
- df.Info()
- df.count())
- df.describe())
- df.mean())

In [32]:
people_df

NameError: name 'people_df' is not defined

In [33]:
people_df.info()

NameError: name 'people_df' is not defined

In [34]:
people_df['name'].describe()

NameError: name 'people_df' is not defined

In [35]:
people_df.count()

NameError: name 'people_df' is not defined

In [36]:
x=[1,3,4,50]
print(np.median(x))
print(np.mean(x))

3.5
14.5


In [37]:
#print(df,"\n")
people_df.info()
#print("df.count()  \n",df.count())
#print("\n df.describe() \n",df.describe())
#print("\n df.mean() \n",df.mean())

NameError: name 'people_df' is not defined

### Pandas Data Frame operations

In [38]:
Image("res/CRUD.png")

FileNotFoundError: No such file or directory: 'res/CRUD.png'

FileNotFoundError: No such file or directory: 'res/CRUD.png'

<IPython.core.display.Image object>

### Data Frame creation
You can create/form a Data Frame from:
- Dict of 1D ndarrays, lists, dicts, or Series

- 2-D numpy.ndarray

- Structured or record ndarray

- A Series

- Another DataFrame

#### Here is an example...

In [39]:
print('example_df = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}\n')

example_dict = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}

example_dict

example_df = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}



{'col1': [1.0, 2.0, 3.0, 4.0], 'col2': [4.0, 3.0, 2.0, 1.0]}

In [40]:
df=pd.DataFrame(example_dict,index =['a','b','c','d'])

In [41]:
df

col1  col2
a   1.0   4.0
b   2.0   3.0
c   3.0   2.0
d   4.0   1.0

#### creating Index for the Data frame...

In [42]:
names = ['Gen','Yan','Ira', 'Kaan']
food = ['dumpling', 'pierogi','pasta','caj']
food_dic = {'names': names,'fav_food': food}
food_df = pd.DataFrame(food_dic)
food_df

names  fav_food
0   Gen  dumpling
1   Yan   pierogi
2   Ira     pasta
3  Kaan       caj

In [43]:
names_2 = ['Anas','Bryan']
food_2 = ['biriyani', 'irish stew']
food_dict_2 = {'name': names_2,'fav_food':food_2}
food_df2 = pd.DataFrame([food_df, food_df2)
food_df2

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (3212804554.py, line 4)

In [44]:
df = pd.concat([food_df,food_df2])
df

names    fav_food   name
0   Gen    dumpling    NaN
1   Yan     pierogi    NaN
2   Ira       pasta    NaN
3  Kaan         caj    NaN
0   NaN    biriyani   Anas
1   NaN  irish stew  Bryan

In [45]:
df.reset_index(drop = True, inplace = True)
df

names    fav_food   name
0   Gen    dumpling    NaN
1   Yan     pierogi    NaN
2   Ira       pasta    NaN
3  Kaan         caj    NaN
4   NaN    biriyani   Anas
5   NaN  irish stew  Bryan

In [46]:
print('dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}\n')

dict2= {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}

dict2

dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}



{'col1': [1.0, 2.0, 3.0, 4.0], 'col2': [4.0, 3.0, 2.0, 1.0]}

In [47]:
df2=pd.DataFrame(dic2)
df2

NameError: name 'dic2' is not defined

In [48]:
df3 = pd.concat([df,df2], axis=0)

NameError: name 'df2' is not defined

In [49]:
df3.reset_index()

NameError: name 'df3' is not defined

### Creating a Data frame from Pandas Series objects.. 

In [50]:
d = {
       "apples": [3, 2, 0,1],
        "oranges": [0, 3, 7, 2],
    }

pd.DataFrame(d)

apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [51]:
Image("res/series-and-dataframe.width-1200.png")

FileNotFoundError: No such file or directory: 'res/series-and-dataframe.width-1200.png'

FileNotFoundError: No such file or directory: 'res/series-and-dataframe.width-1200.png'

<IPython.core.display.Image object>

source: https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png

### Data Frame Selection / Indexing

In [24]:
data = {
    'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
    'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
             'Manchester', 'Cairo', 'Osaka'],
    'age': [41, 28, 33, 34, 38, 31, 37],
    'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = [101, 102, 103, 104, 105, 106, 107]
students_df = pd.DataFrame(data=data, index=row_labels)
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [25]:
students_df.index

Int64Index([101, 102, 103, 104, 105, 106, 107], dtype='int64')

In [26]:
students_df=students_df.drop(105)

In [27]:
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [28]:
students_df.reset_index(drop=True)

name         city  age  py-score
0  Xavier  Mexico City   41      88.0
1     Ann      Toronto   28      79.0
2    Jana       Prague   33      81.0
3      Yi     Shanghai   34      80.0
4    Amal        Cairo   31      61.0
5    Nori        Osaka   37      84.0

In [29]:
students_df.set_index('name')

city  age  py-score
name                              
Xavier  Mexico City   41      88.0
Ann         Toronto   28      79.0
Jana         Prague   33      81.0
Yi         Shanghai   34      80.0
Amal          Cairo   31      61.0
Nori          Osaka   37      84.0

## Source: https://realpython.com/

### data Selection

In [30]:
students_df.loc[[101],["age"]]

age
101   41

In [31]:
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

### Selecting by Label
- .loc[]  function

In [32]:
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [33]:
#print("students_df.loc[:, 'city']")
#students_df.loc[:, 'city']

In [34]:
print("students_df.loc[102:106, ['name', 'city']]")
students_df.loc[102:106, ['name', 'city']]

students_df.loc[102:106, ['name', 'city']]


name      city
102   Ann   Toronto
103  Jana    Prague
104    Yi  Shanghai
106  Amal     Cairo

In [35]:
#print('df["city"]')
cities = students_df[["name","city"]]
cities

name         city
101  Xavier  Mexico City
102     Ann      Toronto
103    Jana       Prague
104      Yi     Shanghai
106    Amal        Cairo
107    Nori        Osaka

In [36]:
print("df.city")
students_df.city

df.city


101    Mexico City
102        Toronto
103         Prague
104       Shanghai
106          Cairo
107          Osaka
Name: city, dtype: object

### Selecting by Position
- .iloc[]

In [20]:
students_df

NameError: name 'students_df' is not defined

In [38]:
students_df.iloc[0,1]

'Mexico City'

In [39]:
print("students_df.iloc[1:6, [0, 1]]")
students_df.iloc[1:6, [0, 1]]

students_df.iloc[1:6, [0, 1]]


name      city
102   Ann   Toronto
103  Jana    Prague
104    Yi  Shanghai
106  Amal     Cairo
107  Nori     Osaka

### Hmm.. Can you tell what is the difference between loc and iloc?

### Setting/ Updating data

#### let us first update the Data frame index..

In [40]:
students_df

name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [42]:
students_df.index = list(np.arange(0, 6))
students_df

name         city  age  py-score
0  Xavier  Mexico City   41      88.0
1     Ann      Toronto   28      79.0
2    Jana       Prague   33      81.0
3      Yi     Shanghai   34      80.0
4    Amal        Cairo   31      61.0
5    Nori        Osaka   37      84.0

In [43]:
students_df.index

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [44]:
students_df.iloc[:4, 3] = [40, 50, 60, 70]
students_df

name         city  age  py-score
0  Xavier  Mexico City   41      40.0
1     Ann      Toronto   28      50.0
2    Jana       Prague   33      60.0
3      Yi     Shanghai   34      70.0
4    Amal        Cairo   31      61.0
5    Nori        Osaka   37      84.0

In [45]:
students_df.loc[5, 'py-score'] 

84.0

In [46]:
students_df.loc[5, 'py-score'] = 70
students_df

name         city  age  py-score
0  Xavier  Mexico City   41      40.0
1     Ann      Toronto   28      50.0
2    Jana       Prague   33      60.0
3      Yi     Shanghai   34      70.0
4    Amal        Cairo   31      61.0
5    Nori        Osaka   37      70.0

In [47]:
students_df.loc[:,"py-score"]=90 
students_df

name         city  age  py-score
0  Xavier  Mexico City   41        90
1     Ann      Toronto   28        90
2    Jana       Prague   33        90
3      Yi     Shanghai   34        90
4    Amal        Cairo   31        90
5    Nori        Osaka   37        90

In [53]:
students_df.iloc[:, -1] = [88.0, 90, 81.0, 80.0, 68.0, 61.0]
students_df

name         city  age  py-score
0  Xavier  Mexico City   41      88.0
1     Ann      Toronto   28      90.0
2    Jana       Prague   33      81.0
3      Yi     Shanghai   34      80.0
4    Amal        Cairo   31      68.0
5    Nori        Osaka   37      61.0

In [54]:
students_df

name         city  age  py-score
0  Xavier  Mexico City   41      88.0
1     Ann      Toronto   28      90.0
2    Jana       Prague   33      81.0
3      Yi     Shanghai   34      80.0
4    Amal        Cairo   31      68.0
5    Nori        Osaka   37      61.0

In [55]:
students_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      6 non-null      object 
 1   city      6 non-null      object 
 2   age       6 non-null      int64  
 3   py-score  6 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 412.0+ bytes


In [56]:
students_df["py-score"] =  students_df["py-score"]*1.5

In [57]:
students_df

name         city  age  py-score
0  Xavier  Mexico City   41     132.0
1     Ann      Toronto   28     135.0
2    Jana       Prague   33     121.5
3      Yi     Shanghai   34     120.0
4    Amal        Cairo   31     102.0
5    Nori        Osaka   37      91.5

In [58]:
students_df["py-score"]=list(map(lambda x: x+10,students_df["py-score"]))

In [59]:
students_df["py-score"] =  students_df["py-score"]*10


In [60]:
students_df

name         city  age  py-score
0  Xavier  Mexico City   41    1420.0
1     Ann      Toronto   28    1450.0
2    Jana       Prague   33    1315.0
3      Yi     Shanghai   34    1300.0
4    Amal        Cairo   31    1120.0
5    Nori        Osaka   37    1015.0

In [19]:
students_df

NameError: name 'students_df' is not defined

In [18]:
type(students_df[["age"]])

NameError: name 'students_df' is not defined

### Inserting/deleting rows

In [16]:
students_df['country'] = ['Mexico', 'Canada', 'Czech Republic', 'China', 'UK', 'Egypt', 'Japan']

NameError: name 'students_df' is not defined

In [64]:
name = ['Juan', 'Monika', 'Juliette']
city = ['Berlin','Paris', 'Paris']
age = [30,20,25]

new_students = { 'name' : name, 'city':city, 'age':age}

In [65]:
new_df = pd.DataFrame(new_students)
new_df

name    city  age
0      Juan  Berlin   30
1    Monika   Paris   20
2  Juliette   Paris   25

In [66]:
df = pd.concat([students_df,new_df])

In [67]:
df.reset_index(drop=True, inplace=True)

In [68]:
df

name         city  age  py-score
0    Xavier  Mexico City   41    1420.0
1       Ann      Toronto   28    1450.0
2      Jana       Prague   33    1315.0
3        Yi     Shanghai   34    1300.0
4      Amal        Cairo   31    1120.0
5      Nori        Osaka   37    1015.0
6      Juan       Berlin   30       NaN
7    Monika        Paris   20       NaN
8  Juliette        Paris   25       NaN

In [69]:
students_df  = students_df[['name', 'city', 'age', 'py-score']]
students_df

name         city  age  py-score
0  Xavier  Mexico City   41    1420.0
1     Ann      Toronto   28    1450.0
2    Jana       Prague   33    1315.0
3      Yi     Shanghai   34    1300.0
4    Amal        Cairo   31    1120.0
5    Nori        Osaka   37    1015.0

In [70]:
Ronald = pd.Series(data=['Ronald', 'Berlin', 34, 79],
                 index=students_df.columns[0:4])
students_df= students_df.append(Ronald, ignore_index=True)
students_df

name         city  age  py-score
0  Xavier  Mexico City   41    1420.0
1     Ann      Toronto   28    1450.0
2    Jana       Prague   33    1315.0
3      Yi     Shanghai   34    1300.0
4    Amal        Cairo   31    1120.0
5    Nori        Osaka   37    1015.0
6  Ronald       Berlin   34      79.0

In [72]:
students_df.iloc[6,:]

name        Ronald
city        Berlin
age             34
py-score      79.0
Name: 6, dtype: object

### Inserting/Deleting columns

In [74]:
#print('df[js-score] = np.array([71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0])')
students_df['js-score'] =[71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80]
students_df

name         city  age  py-score  js-score
0  Xavier  Mexico City   41    1420.0      71.0
1     Ann      Toronto   28    1450.0      95.0
2    Jana       Prague   33    1315.0      88.0
3      Yi     Shanghai   34    1300.0      79.0
4    Amal        Cairo   31    1120.0      91.0
5    Nori        Osaka   37    1015.0      91.0
6  Ronald       Berlin   34      79.0      80.0

In [75]:
students_df['py-score-updated'] = students_df['py-score'] * 10 

In [76]:
students_df

name         city  age  py-score  js-score  py-score-updated
0  Xavier  Mexico City   41    1420.0      71.0           14200.0
1     Ann      Toronto   28    1450.0      95.0           14500.0
2    Jana       Prague   33    1315.0      88.0           13150.0
3      Yi     Shanghai   34    1300.0      79.0           13000.0
4    Amal        Cairo   31    1120.0      91.0           11200.0
5    Nori        Osaka   37    1015.0      91.0           10150.0
6  Ronald       Berlin   34      79.0      80.0             790.0

### Inserting in a specific location

In [77]:
#print('df.insert(loc=4, column=js-score,value=np.array([86.0, 81.0, 78.0, 88.0, 74.0, 70.0, 81.0]))')
students_df.insert(loc=4, column='django-score',
          value=np.array([70, 74, 78, 56, 66, 78, 81.0]))
students_df

name         city  age  py-score  django-score  js-score  \
0  Xavier  Mexico City   41    1420.0          70.0      71.0   
1     Ann      Toronto   28    1450.0          74.0      95.0   
2    Jana       Prague   33    1315.0          78.0      88.0   
3      Yi     Shanghai   34    1300.0          56.0      79.0   
4    Amal        Cairo   31    1120.0          66.0      91.0   
5    Nori        Osaka   37    1015.0          78.0      91.0   
6  Ronald       Berlin   34      79.0          81.0      80.0   

   py-score-updated  
0           14200.0  
1           14500.0  
2           13150.0  
3           13000.0  
4           11200.0  
5           10150.0  
6             790.0

### dropping specific column

In [ ]:
## axis= 0 dropping by row,  axis=1 dropping by column
students_df.drop(labels=['django-score'], axis=1)

### Filtering/Boolean Indexing

In [78]:
students_df["py-score"] >= 75

0    True
1    True
2    True
3    True
4    True
5    True
6    True
Name: py-score, dtype: bool

In [79]:
very_good_students_filter=students_df[students_df["py-score"]>=75]

In [80]:
very_good_students_filter

name         city  age  py-score  django-score  js-score  \
0  Xavier  Mexico City   41    1420.0          70.0      71.0   
1     Ann      Toronto   28    1450.0          74.0      95.0   
2    Jana       Prague   33    1315.0          78.0      88.0   
3      Yi     Shanghai   34    1300.0          56.0      79.0   
4    Amal        Cairo   31    1120.0          66.0      91.0   
5    Nori        Osaka   37    1015.0          78.0      91.0   
6  Ronald       Berlin   34      79.0          81.0      80.0   

   py-score-updated  
0           14200.0  
1           14500.0  
2           13150.0  
3           13000.0  
4           11200.0  
5           10150.0  
6             790.0

### Creating powerful filters with Logical operators AND, OR, NOT, XOR

In [81]:
#print('df[(df[py-score] >= 80) & (df[js-score] >= 80)]')
students_df[(students_df['py-score'] >= 200) | (students_df['django-score'] >= 80)] #or 

name         city  age  py-score  django-score  js-score  \
0  Xavier  Mexico City   41    1420.0          70.0      71.0   
1     Ann      Toronto   28    1450.0          74.0      95.0   
2    Jana       Prague   33    1315.0          78.0      88.0   
3      Yi     Shanghai   34    1300.0          56.0      79.0   
4    Amal        Cairo   31    1120.0          66.0      91.0   
5    Nori        Osaka   37    1015.0          78.0      91.0   
6  Ronald       Berlin   34      79.0          81.0      80.0   

   py-score-updated  
0           14200.0  
1           14500.0  
2           13150.0  
3           13000.0  
4           11200.0  
5           10150.0  
6             790.0

## using value counts  function

In [13]:
people_df=pd.read_csv("data/people.csv")
people_df

name  age country
0    Pol   22      ES
1   Javi   20      ES
2  Maria   23      AR
3   Anna   24      FR
4   Anna   24      UK
5   Javi   30      MA
6    Dog    2      XX

In [15]:
people_df['name'].value_counts()

Javi     2
Anna     2
Pol      1
Maria    1
Dog      1
Name: name, dtype: int64

In [ ]:
people_df.to_csv('people_numpy.csv') #this is the function for converting the data set into csv